when:
  - event: [push, pull_request]
    branch: [master]

steps:
  - name: build
    image: rocq/rocq-prover:9.0.1-ocaml-4.14.2-flambda
    commands:
      - opam install -y coq-hammer-tactics coq-stdpp rocq-autosubst-ocaml
      - eval $(opam env)
      - sudo chown -R 1000:1000 .
      - make -j2 theories
