when:
  - event: [push, pull_request]
    branch: [master]

steps:
  - name: build
    image: coqorg/coq:8.20.1-ocaml-4.14.2-flambda
    commands:
      - opam install -y coq-hammer-tactics coq-equations coq-stdpp coq-autosubst-ocaml
      - eval $(opam env)
      - sudo chown -R 1000:1000 .
      - make -j2
